package com.flycode.person.entity;

public class Person {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_2.id
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_2.sj_id
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    private String sjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_2.company_nature
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    private String companyNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_2.name
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_2.company_job
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    private String companyJob;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_2.tel
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_2.id
     *
     * @return the value of SCM_project_2.id
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_2.id
     *
     * @param id the value for SCM_project_2.id
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_2.sj_id
     *
     * @return the value of SCM_project_2.sj_id
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public String getSjId() {
        return sjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_2.sj_id
     *
     * @param sjId the value for SCM_project_2.sj_id
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public void setSjId(String sjId) {
        this.sjId = sjId == null ? null : sjId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_2.company_nature
     *
     * @return the value of SCM_project_2.company_nature
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public String getCompanyNature() {
        return companyNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_2.company_nature
     *
     * @param companyNature the value for SCM_project_2.company_nature
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public void setCompanyNature(String companyNature) {
        this.companyNature = companyNature == null ? null : companyNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_2.name
     *
     * @return the value of SCM_project_2.name
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_2.name
     *
     * @param name the value for SCM_project_2.name
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_2.company_job
     *
     * @return the value of SCM_project_2.company_job
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public String getCompanyJob() {
        return companyJob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_2.company_job
     *
     * @param companyJob the value for SCM_project_2.company_job
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public void setCompanyJob(String companyJob) {
        this.companyJob = companyJob == null ? null : companyJob.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_2.tel
     *
     * @return the value of SCM_project_2.tel
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_2.tel
     *
     * @param tel the value for SCM_project_2.tel
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }
}