package com.flycode.sj.entity;

import java.util.Date;

public class SJ {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.sj_id
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String sjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.project_name
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.address
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.product_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.project_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String projectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.area
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.union_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String unionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.bridge_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String bridgeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.bridge_span
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String bridgeSpan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.project_nature
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String projectNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.comment
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.openid
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.create_date
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.update_date
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project.status
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.sj_id
     *
     * @return the value of SCM_project.sj_id
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getSjId() {
        return sjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.sj_id
     *
     * @param sjId the value for SCM_project.sj_id
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setSjId(String sjId) {
        this.sjId = sjId == null ? null : sjId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.project_name
     *
     * @return the value of SCM_project.project_name
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.project_name
     *
     * @param projectName the value for SCM_project.project_name
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.address
     *
     * @return the value of SCM_project.address
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.address
     *
     * @param address the value for SCM_project.address
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.product_type
     *
     * @return the value of SCM_project.product_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.product_type
     *
     * @param productType the value for SCM_project.product_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setProductType(String productType) {
        this.productType = productType == null ? null : productType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.project_type
     *
     * @return the value of SCM_project.project_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.project_type
     *
     * @param projectType the value for SCM_project.project_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setProjectType(String projectType) {
        this.projectType = projectType == null ? null : projectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.area
     *
     * @return the value of SCM_project.area
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.area
     *
     * @param area the value for SCM_project.area
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.union_type
     *
     * @return the value of SCM_project.union_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getUnionType() {
        return unionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.union_type
     *
     * @param unionType the value for SCM_project.union_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setUnionType(String unionType) {
        this.unionType = unionType == null ? null : unionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.bridge_type
     *
     * @return the value of SCM_project.bridge_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getBridgeType() {
        return bridgeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.bridge_type
     *
     * @param bridgeType the value for SCM_project.bridge_type
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setBridgeType(String bridgeType) {
        this.bridgeType = bridgeType == null ? null : bridgeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.bridge_span
     *
     * @return the value of SCM_project.bridge_span
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getBridgeSpan() {
        return bridgeSpan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.bridge_span
     *
     * @param bridgeSpan the value for SCM_project.bridge_span
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setBridgeSpan(String bridgeSpan) {
        this.bridgeSpan = bridgeSpan == null ? null : bridgeSpan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.project_nature
     *
     * @return the value of SCM_project.project_nature
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getProjectNature() {
        return projectNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.project_nature
     *
     * @param projectNature the value for SCM_project.project_nature
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setProjectNature(String projectNature) {
        this.projectNature = projectNature == null ? null : projectNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.comment
     *
     * @return the value of SCM_project.comment
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.comment
     *
     * @param comment the value for SCM_project.comment
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.openid
     *
     * @return the value of SCM_project.openid
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.openid
     *
     * @param openid the value for SCM_project.openid
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.create_date
     *
     * @return the value of SCM_project.create_date
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.create_date
     *
     * @param createDate the value for SCM_project.create_date
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.update_date
     *
     * @return the value of SCM_project.update_date
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.update_date
     *
     * @param updateDate the value for SCM_project.update_date
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project.status
     *
     * @return the value of SCM_project.status
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project.status
     *
     * @param status the value for SCM_project.status
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}