package com.flycode.sj.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SJExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public SJExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSjIdIsNull() {
            addCriterion("sj_id is null");
            return (Criteria) this;
        }

        public Criteria andSjIdIsNotNull() {
            addCriterion("sj_id is not null");
            return (Criteria) this;
        }

        public Criteria andSjIdEqualTo(String value) {
            addCriterion("sj_id =", value, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdNotEqualTo(String value) {
            addCriterion("sj_id <>", value, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdGreaterThan(String value) {
            addCriterion("sj_id >", value, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdGreaterThanOrEqualTo(String value) {
            addCriterion("sj_id >=", value, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdLessThan(String value) {
            addCriterion("sj_id <", value, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdLessThanOrEqualTo(String value) {
            addCriterion("sj_id <=", value, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdLike(String value) {
            addCriterion("sj_id like", value, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdNotLike(String value) {
            addCriterion("sj_id not like", value, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdIn(List<String> values) {
            addCriterion("sj_id in", values, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdNotIn(List<String> values) {
            addCriterion("sj_id not in", values, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdBetween(String value1, String value2) {
            addCriterion("sj_id between", value1, value2, "sjId");
            return (Criteria) this;
        }

        public Criteria andSjIdNotBetween(String value1, String value2) {
            addCriterion("sj_id not between", value1, value2, "sjId");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("project_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("project_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("project_name =", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("project_name <>", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("project_name >", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_name >=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("project_name <", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("project_name <=", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("project_name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("project_name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("project_name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("project_name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("project_name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("project_name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("product_type is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("product_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(String value) {
            addCriterion("product_type =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(String value) {
            addCriterion("product_type <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(String value) {
            addCriterion("product_type >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(String value) {
            addCriterion("product_type >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(String value) {
            addCriterion("product_type <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(String value) {
            addCriterion("product_type <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLike(String value) {
            addCriterion("product_type like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotLike(String value) {
            addCriterion("product_type not like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<String> values) {
            addCriterion("product_type in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<String> values) {
            addCriterion("product_type not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(String value1, String value2) {
            addCriterion("product_type between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(String value1, String value2) {
            addCriterion("product_type not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIsNull() {
            addCriterion("project_type is null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIsNotNull() {
            addCriterion("project_type is not null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeEqualTo(String value) {
            addCriterion("project_type =", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotEqualTo(String value) {
            addCriterion("project_type <>", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeGreaterThan(String value) {
            addCriterion("project_type >", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("project_type >=", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLessThan(String value) {
            addCriterion("project_type <", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLessThanOrEqualTo(String value) {
            addCriterion("project_type <=", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeLike(String value) {
            addCriterion("project_type like", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotLike(String value) {
            addCriterion("project_type not like", value, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIn(List<String> values) {
            addCriterion("project_type in", values, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotIn(List<String> values) {
            addCriterion("project_type not in", values, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeBetween(String value1, String value2) {
            addCriterion("project_type between", value1, value2, "projectType");
            return (Criteria) this;
        }

        public Criteria andProjectTypeNotBetween(String value1, String value2) {
            addCriterion("project_type not between", value1, value2, "projectType");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andUnionTypeIsNull() {
            addCriterion("union_type is null");
            return (Criteria) this;
        }

        public Criteria andUnionTypeIsNotNull() {
            addCriterion("union_type is not null");
            return (Criteria) this;
        }

        public Criteria andUnionTypeEqualTo(String value) {
            addCriterion("union_type =", value, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeNotEqualTo(String value) {
            addCriterion("union_type <>", value, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeGreaterThan(String value) {
            addCriterion("union_type >", value, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("union_type >=", value, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeLessThan(String value) {
            addCriterion("union_type <", value, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeLessThanOrEqualTo(String value) {
            addCriterion("union_type <=", value, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeLike(String value) {
            addCriterion("union_type like", value, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeNotLike(String value) {
            addCriterion("union_type not like", value, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeIn(List<String> values) {
            addCriterion("union_type in", values, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeNotIn(List<String> values) {
            addCriterion("union_type not in", values, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeBetween(String value1, String value2) {
            addCriterion("union_type between", value1, value2, "unionType");
            return (Criteria) this;
        }

        public Criteria andUnionTypeNotBetween(String value1, String value2) {
            addCriterion("union_type not between", value1, value2, "unionType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeIsNull() {
            addCriterion("bridge_type is null");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeIsNotNull() {
            addCriterion("bridge_type is not null");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeEqualTo(String value) {
            addCriterion("bridge_type =", value, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeNotEqualTo(String value) {
            addCriterion("bridge_type <>", value, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeGreaterThan(String value) {
            addCriterion("bridge_type >", value, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("bridge_type >=", value, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeLessThan(String value) {
            addCriterion("bridge_type <", value, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeLessThanOrEqualTo(String value) {
            addCriterion("bridge_type <=", value, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeLike(String value) {
            addCriterion("bridge_type like", value, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeNotLike(String value) {
            addCriterion("bridge_type not like", value, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeIn(List<String> values) {
            addCriterion("bridge_type in", values, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeNotIn(List<String> values) {
            addCriterion("bridge_type not in", values, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeBetween(String value1, String value2) {
            addCriterion("bridge_type between", value1, value2, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeTypeNotBetween(String value1, String value2) {
            addCriterion("bridge_type not between", value1, value2, "bridgeType");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanIsNull() {
            addCriterion("bridge_span is null");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanIsNotNull() {
            addCriterion("bridge_span is not null");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanEqualTo(String value) {
            addCriterion("bridge_span =", value, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanNotEqualTo(String value) {
            addCriterion("bridge_span <>", value, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanGreaterThan(String value) {
            addCriterion("bridge_span >", value, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanGreaterThanOrEqualTo(String value) {
            addCriterion("bridge_span >=", value, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanLessThan(String value) {
            addCriterion("bridge_span <", value, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanLessThanOrEqualTo(String value) {
            addCriterion("bridge_span <=", value, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanLike(String value) {
            addCriterion("bridge_span like", value, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanNotLike(String value) {
            addCriterion("bridge_span not like", value, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanIn(List<String> values) {
            addCriterion("bridge_span in", values, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanNotIn(List<String> values) {
            addCriterion("bridge_span not in", values, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanBetween(String value1, String value2) {
            addCriterion("bridge_span between", value1, value2, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andBridgeSpanNotBetween(String value1, String value2) {
            addCriterion("bridge_span not between", value1, value2, "bridgeSpan");
            return (Criteria) this;
        }

        public Criteria andProjectNatureIsNull() {
            addCriterion("project_nature is null");
            return (Criteria) this;
        }

        public Criteria andProjectNatureIsNotNull() {
            addCriterion("project_nature is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNatureEqualTo(String value) {
            addCriterion("project_nature =", value, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureNotEqualTo(String value) {
            addCriterion("project_nature <>", value, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureGreaterThan(String value) {
            addCriterion("project_nature >", value, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureGreaterThanOrEqualTo(String value) {
            addCriterion("project_nature >=", value, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureLessThan(String value) {
            addCriterion("project_nature <", value, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureLessThanOrEqualTo(String value) {
            addCriterion("project_nature <=", value, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureLike(String value) {
            addCriterion("project_nature like", value, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureNotLike(String value) {
            addCriterion("project_nature not like", value, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureIn(List<String> values) {
            addCriterion("project_nature in", values, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureNotIn(List<String> values) {
            addCriterion("project_nature not in", values, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureBetween(String value1, String value2) {
            addCriterion("project_nature between", value1, value2, "projectNature");
            return (Criteria) this;
        }

        public Criteria andProjectNatureNotBetween(String value1, String value2) {
            addCriterion("project_nature not between", value1, value2, "projectNature");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("`comment` is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("`comment` is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("`comment` =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("`comment` <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("`comment` >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("`comment` >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("`comment` <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("`comment` <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("`comment` like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("`comment` not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("`comment` in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("`comment` not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("`comment` between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("`comment` not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("openid is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("openid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("openid =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("openid <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("openid >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("openid >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("openid <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("openid <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("openid like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("openid not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("openid in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("openid not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("openid between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("openid not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("update_date =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("update_date >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("update_date <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("update_date in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SCM_project
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 14 21:51:50 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SCM_project
     *
     * @mbggenerated Wed Oct 14 21:51:50 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}