package com.flycode.amount.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Amount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_1.sj_id
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    private String sjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_1.amount
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_1.order_date
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_1.owner_unit
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    private String ownerUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_1.design_school
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    private String designSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_1.construction_unit
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    private String constructionUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_1.bid_unit
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    private String bidUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_1.leader
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    private String leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_1.help_person
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    private String helpPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_1.project_property
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    private String projectProperty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_1.sj_id
     *
     * @return the value of SCM_project_1.sj_id
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public String getSjId() {
        return sjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_1.sj_id
     *
     * @param sjId the value for SCM_project_1.sj_id
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public void setSjId(String sjId) {
        this.sjId = sjId == null ? null : sjId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_1.amount
     *
     * @return the value of SCM_project_1.amount
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_1.amount
     *
     * @param amount the value for SCM_project_1.amount
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_1.order_date
     *
     * @return the value of SCM_project_1.order_date
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_1.order_date
     *
     * @param orderDate the value for SCM_project_1.order_date
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_1.owner_unit
     *
     * @return the value of SCM_project_1.owner_unit
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public String getOwnerUnit() {
        return ownerUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_1.owner_unit
     *
     * @param ownerUnit the value for SCM_project_1.owner_unit
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public void setOwnerUnit(String ownerUnit) {
        this.ownerUnit = ownerUnit == null ? null : ownerUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_1.design_school
     *
     * @return the value of SCM_project_1.design_school
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public String getDesignSchool() {
        return designSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_1.design_school
     *
     * @param designSchool the value for SCM_project_1.design_school
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public void setDesignSchool(String designSchool) {
        this.designSchool = designSchool == null ? null : designSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_1.construction_unit
     *
     * @return the value of SCM_project_1.construction_unit
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public String getConstructionUnit() {
        return constructionUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_1.construction_unit
     *
     * @param constructionUnit the value for SCM_project_1.construction_unit
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public void setConstructionUnit(String constructionUnit) {
        this.constructionUnit = constructionUnit == null ? null : constructionUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_1.bid_unit
     *
     * @return the value of SCM_project_1.bid_unit
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public String getBidUnit() {
        return bidUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_1.bid_unit
     *
     * @param bidUnit the value for SCM_project_1.bid_unit
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public void setBidUnit(String bidUnit) {
        this.bidUnit = bidUnit == null ? null : bidUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_1.leader
     *
     * @return the value of SCM_project_1.leader
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_1.leader
     *
     * @param leader the value for SCM_project_1.leader
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_1.help_person
     *
     * @return the value of SCM_project_1.help_person
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public String getHelpPerson() {
        return helpPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_1.help_person
     *
     * @param helpPerson the value for SCM_project_1.help_person
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public void setHelpPerson(String helpPerson) {
        this.helpPerson = helpPerson == null ? null : helpPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_1.project_property
     *
     * @return the value of SCM_project_1.project_property
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public String getProjectProperty() {
        return projectProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_1.project_property
     *
     * @param projectProperty the value for SCM_project_1.project_property
     *
     * @mbggenerated Wed Oct 14 21:58:23 CST 2015
     */
    public void setProjectProperty(String projectProperty) {
        this.projectProperty = projectProperty == null ? null : projectProperty.trim();
    }
}