package com.flycode.alliance.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CPAllianceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public CPAllianceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("Code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("Code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("Code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("Code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("Code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("Code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("Code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("Code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("Code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("Code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("Code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("Code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("Code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`Name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`Name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`Name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`Name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`Name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`Name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`Name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`Name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`Name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`Name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`Name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`Name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`Name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`Name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andForeignnameIsNull() {
            addCriterion("ForeignName is null");
            return (Criteria) this;
        }

        public Criteria andForeignnameIsNotNull() {
            addCriterion("ForeignName is not null");
            return (Criteria) this;
        }

        public Criteria andForeignnameEqualTo(String value) {
            addCriterion("ForeignName =", value, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameNotEqualTo(String value) {
            addCriterion("ForeignName <>", value, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameGreaterThan(String value) {
            addCriterion("ForeignName >", value, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameGreaterThanOrEqualTo(String value) {
            addCriterion("ForeignName >=", value, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameLessThan(String value) {
            addCriterion("ForeignName <", value, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameLessThanOrEqualTo(String value) {
            addCriterion("ForeignName <=", value, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameLike(String value) {
            addCriterion("ForeignName like", value, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameNotLike(String value) {
            addCriterion("ForeignName not like", value, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameIn(List<String> values) {
            addCriterion("ForeignName in", values, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameNotIn(List<String> values) {
            addCriterion("ForeignName not in", values, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameBetween(String value1, String value2) {
            addCriterion("ForeignName between", value1, value2, "foreignname");
            return (Criteria) this;
        }

        public Criteria andForeignnameNotBetween(String value1, String value2) {
            addCriterion("ForeignName not between", value1, value2, "foreignname");
            return (Criteria) this;
        }

        public Criteria andNodetypeIsNull() {
            addCriterion("NodeType is null");
            return (Criteria) this;
        }

        public Criteria andNodetypeIsNotNull() {
            addCriterion("NodeType is not null");
            return (Criteria) this;
        }

        public Criteria andNodetypeEqualTo(Integer value) {
            addCriterion("NodeType =", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeNotEqualTo(Integer value) {
            addCriterion("NodeType <>", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeGreaterThan(Integer value) {
            addCriterion("NodeType >", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("NodeType >=", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeLessThan(Integer value) {
            addCriterion("NodeType <", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeLessThanOrEqualTo(Integer value) {
            addCriterion("NodeType <=", value, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeIn(List<Integer> values) {
            addCriterion("NodeType in", values, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeNotIn(List<Integer> values) {
            addCriterion("NodeType not in", values, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeBetween(Integer value1, Integer value2) {
            addCriterion("NodeType between", value1, value2, "nodetype");
            return (Criteria) this;
        }

        public Criteria andNodetypeNotBetween(Integer value1, Integer value2) {
            addCriterion("NodeType not between", value1, value2, "nodetype");
            return (Criteria) this;
        }

        public Criteria andCorpidIsNull() {
            addCriterion("CorpID is null");
            return (Criteria) this;
        }

        public Criteria andCorpidIsNotNull() {
            addCriterion("CorpID is not null");
            return (Criteria) this;
        }

        public Criteria andCorpidEqualTo(Integer value) {
            addCriterion("CorpID =", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidNotEqualTo(Integer value) {
            addCriterion("CorpID <>", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidGreaterThan(Integer value) {
            addCriterion("CorpID >", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("CorpID >=", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidLessThan(Integer value) {
            addCriterion("CorpID <", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidLessThanOrEqualTo(Integer value) {
            addCriterion("CorpID <=", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidIn(List<Integer> values) {
            addCriterion("CorpID in", values, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidNotIn(List<Integer> values) {
            addCriterion("CorpID not in", values, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidBetween(Integer value1, Integer value2) {
            addCriterion("CorpID between", value1, value2, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidNotBetween(Integer value1, Integer value2) {
            addCriterion("CorpID not between", value1, value2, "corpid");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`Status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`Status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("`Status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("`Status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("`Status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("`Status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("`Status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("`Status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("`Status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("`Status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("`Status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("`Status` not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatebyidIsNull() {
            addCriterion("CreateByID is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyidIsNotNull() {
            addCriterion("CreateByID is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyidEqualTo(Integer value) {
            addCriterion("CreateByID =", value, "createbyid");
            return (Criteria) this;
        }

        public Criteria andCreatebyidNotEqualTo(Integer value) {
            addCriterion("CreateByID <>", value, "createbyid");
            return (Criteria) this;
        }

        public Criteria andCreatebyidGreaterThan(Integer value) {
            addCriterion("CreateByID >", value, "createbyid");
            return (Criteria) this;
        }

        public Criteria andCreatebyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("CreateByID >=", value, "createbyid");
            return (Criteria) this;
        }

        public Criteria andCreatebyidLessThan(Integer value) {
            addCriterion("CreateByID <", value, "createbyid");
            return (Criteria) this;
        }

        public Criteria andCreatebyidLessThanOrEqualTo(Integer value) {
            addCriterion("CreateByID <=", value, "createbyid");
            return (Criteria) this;
        }

        public Criteria andCreatebyidIn(List<Integer> values) {
            addCriterion("CreateByID in", values, "createbyid");
            return (Criteria) this;
        }

        public Criteria andCreatebyidNotIn(List<Integer> values) {
            addCriterion("CreateByID not in", values, "createbyid");
            return (Criteria) this;
        }

        public Criteria andCreatebyidBetween(Integer value1, Integer value2) {
            addCriterion("CreateByID between", value1, value2, "createbyid");
            return (Criteria) this;
        }

        public Criteria andCreatebyidNotBetween(Integer value1, Integer value2) {
            addCriterion("CreateByID not between", value1, value2, "createbyid");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidIsNull() {
            addCriterion("UpdateByID is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidIsNotNull() {
            addCriterion("UpdateByID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidEqualTo(Integer value) {
            addCriterion("UpdateByID =", value, "updatebyid");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidNotEqualTo(Integer value) {
            addCriterion("UpdateByID <>", value, "updatebyid");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidGreaterThan(Integer value) {
            addCriterion("UpdateByID >", value, "updatebyid");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("UpdateByID >=", value, "updatebyid");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidLessThan(Integer value) {
            addCriterion("UpdateByID <", value, "updatebyid");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidLessThanOrEqualTo(Integer value) {
            addCriterion("UpdateByID <=", value, "updatebyid");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidIn(List<Integer> values) {
            addCriterion("UpdateByID in", values, "updatebyid");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidNotIn(List<Integer> values) {
            addCriterion("UpdateByID not in", values, "updatebyid");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidBetween(Integer value1, Integer value2) {
            addCriterion("UpdateByID between", value1, value2, "updatebyid");
            return (Criteria) this;
        }

        public Criteria andUpdatebyidNotBetween(Integer value1, Integer value2) {
            addCriterion("UpdateByID not between", value1, value2, "updatebyid");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("UpdateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("UpdateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("UpdateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UpdateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("UpdateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UpdateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("UpdateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("UpdateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("UpdateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UpdateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andNotesIsNull() {
            addCriterion("Notes is null");
            return (Criteria) this;
        }

        public Criteria andNotesIsNotNull() {
            addCriterion("Notes is not null");
            return (Criteria) this;
        }

        public Criteria andNotesEqualTo(String value) {
            addCriterion("Notes =", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotEqualTo(String value) {
            addCriterion("Notes <>", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThan(String value) {
            addCriterion("Notes >", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesGreaterThanOrEqualTo(String value) {
            addCriterion("Notes >=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThan(String value) {
            addCriterion("Notes <", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLessThanOrEqualTo(String value) {
            addCriterion("Notes <=", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesLike(String value) {
            addCriterion("Notes like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotLike(String value) {
            addCriterion("Notes not like", value, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesIn(List<String> values) {
            addCriterion("Notes in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotIn(List<String> values) {
            addCriterion("Notes not in", values, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesBetween(String value1, String value2) {
            addCriterion("Notes between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andNotesNotBetween(String value1, String value2) {
            addCriterion("Notes not between", value1, value2, "notes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesIsNull() {
            addCriterion("ForeignNotes is null");
            return (Criteria) this;
        }

        public Criteria andForeignnotesIsNotNull() {
            addCriterion("ForeignNotes is not null");
            return (Criteria) this;
        }

        public Criteria andForeignnotesEqualTo(String value) {
            addCriterion("ForeignNotes =", value, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesNotEqualTo(String value) {
            addCriterion("ForeignNotes <>", value, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesGreaterThan(String value) {
            addCriterion("ForeignNotes >", value, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesGreaterThanOrEqualTo(String value) {
            addCriterion("ForeignNotes >=", value, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesLessThan(String value) {
            addCriterion("ForeignNotes <", value, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesLessThanOrEqualTo(String value) {
            addCriterion("ForeignNotes <=", value, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesLike(String value) {
            addCriterion("ForeignNotes like", value, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesNotLike(String value) {
            addCriterion("ForeignNotes not like", value, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesIn(List<String> values) {
            addCriterion("ForeignNotes in", values, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesNotIn(List<String> values) {
            addCriterion("ForeignNotes not in", values, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesBetween(String value1, String value2) {
            addCriterion("ForeignNotes between", value1, value2, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andForeignnotesNotBetween(String value1, String value2) {
            addCriterion("ForeignNotes not between", value1, value2, "foreignnotes");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("`Level` is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("`Level` is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("`Level` =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("`Level` <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("`Level` >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("`Level` >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("`Level` <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("`Level` <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("`Level` in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("`Level` not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("`Level` between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("`Level` not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andTleftIsNull() {
            addCriterion("TLeft is null");
            return (Criteria) this;
        }

        public Criteria andTleftIsNotNull() {
            addCriterion("TLeft is not null");
            return (Criteria) this;
        }

        public Criteria andTleftEqualTo(Integer value) {
            addCriterion("TLeft =", value, "tleft");
            return (Criteria) this;
        }

        public Criteria andTleftNotEqualTo(Integer value) {
            addCriterion("TLeft <>", value, "tleft");
            return (Criteria) this;
        }

        public Criteria andTleftGreaterThan(Integer value) {
            addCriterion("TLeft >", value, "tleft");
            return (Criteria) this;
        }

        public Criteria andTleftGreaterThanOrEqualTo(Integer value) {
            addCriterion("TLeft >=", value, "tleft");
            return (Criteria) this;
        }

        public Criteria andTleftLessThan(Integer value) {
            addCriterion("TLeft <", value, "tleft");
            return (Criteria) this;
        }

        public Criteria andTleftLessThanOrEqualTo(Integer value) {
            addCriterion("TLeft <=", value, "tleft");
            return (Criteria) this;
        }

        public Criteria andTleftIn(List<Integer> values) {
            addCriterion("TLeft in", values, "tleft");
            return (Criteria) this;
        }

        public Criteria andTleftNotIn(List<Integer> values) {
            addCriterion("TLeft not in", values, "tleft");
            return (Criteria) this;
        }

        public Criteria andTleftBetween(Integer value1, Integer value2) {
            addCriterion("TLeft between", value1, value2, "tleft");
            return (Criteria) this;
        }

        public Criteria andTleftNotBetween(Integer value1, Integer value2) {
            addCriterion("TLeft not between", value1, value2, "tleft");
            return (Criteria) this;
        }

        public Criteria andTrightIsNull() {
            addCriterion("TRight is null");
            return (Criteria) this;
        }

        public Criteria andTrightIsNotNull() {
            addCriterion("TRight is not null");
            return (Criteria) this;
        }

        public Criteria andTrightEqualTo(Integer value) {
            addCriterion("TRight =", value, "tright");
            return (Criteria) this;
        }

        public Criteria andTrightNotEqualTo(Integer value) {
            addCriterion("TRight <>", value, "tright");
            return (Criteria) this;
        }

        public Criteria andTrightGreaterThan(Integer value) {
            addCriterion("TRight >", value, "tright");
            return (Criteria) this;
        }

        public Criteria andTrightGreaterThanOrEqualTo(Integer value) {
            addCriterion("TRight >=", value, "tright");
            return (Criteria) this;
        }

        public Criteria andTrightLessThan(Integer value) {
            addCriterion("TRight <", value, "tright");
            return (Criteria) this;
        }

        public Criteria andTrightLessThanOrEqualTo(Integer value) {
            addCriterion("TRight <=", value, "tright");
            return (Criteria) this;
        }

        public Criteria andTrightIn(List<Integer> values) {
            addCriterion("TRight in", values, "tright");
            return (Criteria) this;
        }

        public Criteria andTrightNotIn(List<Integer> values) {
            addCriterion("TRight not in", values, "tright");
            return (Criteria) this;
        }

        public Criteria andTrightBetween(Integer value1, Integer value2) {
            addCriterion("TRight between", value1, value2, "tright");
            return (Criteria) this;
        }

        public Criteria andTrightNotBetween(Integer value1, Integer value2) {
            addCriterion("TRight not between", value1, value2, "tright");
            return (Criteria) this;
        }

        public Criteria andParentidIsNull() {
            addCriterion("ParentID is null");
            return (Criteria) this;
        }

        public Criteria andParentidIsNotNull() {
            addCriterion("ParentID is not null");
            return (Criteria) this;
        }

        public Criteria andParentidEqualTo(Integer value) {
            addCriterion("ParentID =", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotEqualTo(Integer value) {
            addCriterion("ParentID <>", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThan(Integer value) {
            addCriterion("ParentID >", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ParentID >=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThan(Integer value) {
            addCriterion("ParentID <", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidLessThanOrEqualTo(Integer value) {
            addCriterion("ParentID <=", value, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidIn(List<Integer> values) {
            addCriterion("ParentID in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotIn(List<Integer> values) {
            addCriterion("ParentID not in", values, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidBetween(Integer value1, Integer value2) {
            addCriterion("ParentID between", value1, value2, "parentid");
            return (Criteria) this;
        }

        public Criteria andParentidNotBetween(Integer value1, Integer value2) {
            addCriterion("ParentID not between", value1, value2, "parentid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CP_Alliance
     *
     * @mbggenerated do_not_delete_during_merge Thu Oct 15 14:23:07 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}