package com.flycode.follow.entity;

import java.util.Date;

public class Condition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_3.id
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_3.follow_date
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    private Date followDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_3.stage
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    private String stage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCM_project_3.remark
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_3.id
     *
     * @return the value of SCM_project_3.id
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_3.id
     *
     * @param id the value for SCM_project_3.id
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_3.follow_date
     *
     * @return the value of SCM_project_3.follow_date
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    public Date getFollowDate() {
        return followDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_3.follow_date
     *
     * @param followDate the value for SCM_project_3.follow_date
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    public void setFollowDate(Date followDate) {
        this.followDate = followDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_3.stage
     *
     * @return the value of SCM_project_3.stage
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    public String getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_3.stage
     *
     * @param stage the value for SCM_project_3.stage
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    public void setStage(String stage) {
        this.stage = stage == null ? null : stage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCM_project_3.remark
     *
     * @return the value of SCM_project_3.remark
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCM_project_3.remark
     *
     * @param remark the value for SCM_project_3.remark
     *
     * @mbggenerated Wed Oct 14 22:01:39 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}