package com.flycode.alliance.mapper;

import com.flycode.alliance.entity.CPAlliance;
import com.flycode.alliance.entity.CPAllianceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CPAllianceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    int countByExample(CPAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    int deleteByExample(CPAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    int insert(CPAlliance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    int insertSelective(CPAlliance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    List<CPAlliance> selectByExample(CPAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") CPAlliance record, @Param("example") CPAllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_Alliance
     *
     * @mbggenerated Thu Oct 15 14:23:07 CST 2015
     */
    int updateByExample(@Param("record") CPAlliance record, @Param("example") CPAllianceExample example);
}