package com.flycode.person.mapper;

import com.flycode.person.entity.Person;
import com.flycode.person.entity.PersonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    int countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCM_project_2
     *
     * @mbggenerated Wed Oct 14 21:59:30 CST 2015
     */
    int updateByPrimaryKey(Person record);
}